dat <- read.csv ("/Users/elizaepstein/Desktop/natl2013.csv")
names (dat)
table(dat$pay)
hist(dat$pay)
dev.off()
save(dat, file = "dat2013.RData")
install.packages("dplyr")
library (dplyr)
table (dat$wic)
names(dat$wic)